# Jordan R. Worrobah

## 5/26/2026

# Ex5A NumPy Fundamentals

This notebook practices basic NumPy skills, including creating arrays, checking data types, working with one-dimensional, two-dimensional, and three-dimensional arrays, using indexing, slicing, and transposing arrays.

In [27]:
import numpy as np

## Array Basics

In [28]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [29]:
arr1 = np.array(fruits)

In [30]:
print(arr1)

['apple' 'banana' 'cherry' 'date']


In [31]:
print(arr1.dtype)

<U6


In [32]:
# The dtype returned is <U6.
# The U means Unicode string.
# The 6 means the longest string in the array has 6 characters.

In [33]:
arr2 = np.array([(10, 11, 12), (13, 14, 15)])

In [34]:
print(arr2)

[[10 11 12]
 [13 14 15]]


In [35]:
print(arr2.T)

[[10 13]
 [11 14]
 [12 15]]


In [36]:
arr3 = np.array([(1, 3, 5), (2, 4, 6)])

In [37]:
print(arr3)

[[1 3 5]
 [2 4 6]]


In [38]:
arr4 = np.array([arr3[0, 2], arr3[1, 1]])

In [39]:
print(arr4)

[5 4]


In [40]:
arr5 = np.ones((2, 2, 2))

In [41]:
print(arr5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
