# Exercise 1.A NumPy: Manipulating Arrays

In [16]:
import numpy as np

## Looping Through Arrays

In [17]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])

In [30]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [31]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through the first dimension of the array, which are the rows. 
Each row is multiplied by 2 as a group, so the output stays in array form.

The second loop goes through the second dimension, which are the individual elements inside each row. 
Each number is multiplied and printed separately instead of as part of an array.

In [34]:
for x in arrA:
    for y in x:
        loop_result = y * 2
        print(loop_result)

22
24
26
28
30
32


This loop accesses each individual element in the second dimension,
so each number is doubled and printed separately instead of as rows.

## Joining and Stacking Arrays

In [55]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [56]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [57]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [59]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)

ValueError: all input arrays must have the same shape

This gives an error because the arrays do not have the same shape.
joined_array_1 has shape (4,3) and joined_array_2 has shape (2,6).
np.stack() requires arrays to have identical dimensions.

In [60]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [62]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

This error happens because the arrays have different numbers of rows.
To concatenate on axis=1, both arrays must have the same size along axis=0.

In [75]:
hstack = np.hstack((arrA, arrA))
print(hstack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


Stacking Along Rows

In [76]:
vstack = np.vstack((arrA, arrA))
print(vstack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


Stacking Along Columns

In [77]:
dstack = np.dstack((arrA, arrA))
print(dstack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


Stacking Along Height (depth)

## Splitting Arrays

In [82]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


The result contains 2 arrays.
Each array is 2-dimensional and contains 2 rows and 3 columns.

In [83]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


The result contains 3 arrays.
Each array is still 2-dimensional, but the arrays do not all have the same number of rows.
NumPy splits the rows as evenly as possible.

## Searching and Replacing Array Values

In [84]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [92]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [97]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [99]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
