# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [6]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[11 10]


In [9]:
r_2 = np.random.randint(1, 21, size=(1,2))
print(r_2)

[[18 11]]


In [17]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.25520312]
 [0.6037004 ]]


In [18]:
r_4 = np.random.randint(20, 101, size=(4,5))
print(r_4)

[[55 85 74 86 66]
 [52 53 98 23 29]
 [69 73 90 77 84]
 [61 30 86 50 23]]


In [19]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.35537949 0.50300778 0.54676155 0.2442286  0.7085029 ]
 [0.49452712 0.5675305  0.61779024 0.49068792 0.53553029]
 [0.29255904 0.94095942 0.19996924 0.36201148 0.78030697]
 [0.39796635 0.80292722 0.71929758 0.76635243 0.77392128]]


## Generating Random Choices from

In [21]:
students = np.array(('Leon Poulson', 'Ivana Nwaobi', 'Kenneth Jeffreys',
                      'Shawn Sandman', 'Sincere Jackson', 'Cris Ramiez', 
                      'Lily Wells', 'Dani Trawick', 'Jeremiah Butts', 
                      'Devin Hollingsworth', 'Ebony Dupree', 'Sameul Veloz'))

In [25]:
call_on = np.random.choice(students)
print(call_on)

Sameul Veloz


In [35]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

[['Jeremiah Butts' 'Ebony Dupree' 'Ebony Dupree' 'Lily Wells']
 ['Ivana Nwaobi' 'Lily Wells' 'Sincere Jackson' 'Kenneth Jeffreys']
 ['Jeremiah Butts' 'Sincere Jackson' 'Dani Trawick' 'Sincere Jackson']]


This wouldn't be an effective way to create breakout rooms because it does not protect duplicates. It is possible to have the same person in two diffrent rooms, while it is also possible to have one person not in any rooms. 

In [40]:
call_on_weighted = np.random.choice(students,p=[0, 0.3, 0.1, 0.05, 0.05, 0.1, 0.1, 0.05, 0.05, 0.1, 0.05, 0.05],size=5)
print(call_on_weighted)

['Ivana Nwaobi' 'Cris Ramiez' 'Dani Trawick' 'Kenneth Jeffreys'
 'Ivana Nwaobi']


## Generating a Normal Distribution

In [41]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[11.26850943  7.10380108  3.57823745 15.00196073  9.00733403]
 [11.5337077  18.0074217   8.77783105 12.27609648 17.08315075]
 [11.43223114  5.67348329 13.03308274  8.46279448 17.5935178 ]
 [10.23051913 -0.73219956  9.10805423  5.91352401  9.47786432]]
