# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [8]:
r_1 = np.random.randint(1, 21, size=2)

r_2 = np.random.randint(1, 21, size=(1,2))

r_3 = np.random.rand(2,1)

r_4 = np.random.randint(20, 101, size=(4,5))

r_5 = np.random.rand(4,5)


print("r_1:\n", r_1)
print()
print("nr_2:\n", r_2)
print()
print("nr_3:\n", r_3)
print()
print("nr_4:\n", r_4)
print()
print("nr_5:\n", r_5)

r_1:
 [15 20]

nr_2:
 [[15 19]]

nr_3:
 [[0.89891279]
 [0.25622972]]

nr_4:
 [[20 72 78 75 20]
 [24 86 87 32 34]
 [43 69 69 57 48]
 [63 72 43 39 30]]

nr_5:
 [[0.44566751 0.84774531 0.91873535 0.15097597 0.07996921]
 [0.60521748 0.18020206 0.03135097 0.12635842 0.64535471]
 [0.28726423 0.92763424 0.77642832 0.74117853 0.97959608]
 [0.09507138 0.96704349 0.14244584 0.62738414 0.27754826]]


## Permutations

In [13]:
print(r_4)

[[63 72 43 39 30]
 [43 69 69 57 48]
 [24 86 87 32 34]
 [20 72 78 75 20]]


In [54]:
np.random.shuffle(r_4)
print(r_4)

[[43 69 69 57 48]
 [24 86 87 32 34]
 [63 72 43 39 30]
 [20 72 78 75 20]]


It looks like the numbers are just shuffling up in down in their columns. It does not look like the shuffle is applying to shuffling between columns only between rows.

In [66]:
new_shuffle = np.random.permutation(r_4)
print('\n new_shuffle:')
print(new_shuffle)
print('\n r_4:')
print(r_4)


 new_shuffle:
[[43 69 69 57 48]
 [24 86 87 32 34]
 [20 72 78 75 20]
 [63 72 43 39 30]]

 r_4:
[[43 69 69 57 48]
 [24 86 87 32 34]
 [63 72 43 39 30]
 [20 72 78 75 20]]


You would use shuffle when you want to randomly rearrange the original array itself. 
You would use permutation when you want a shuffled copy while keeping the original array unchanged.

## Mathematical Operations